// Code generated by protoc-gen-go. DO NOT EDIT.
// source: a.proto

package basicmessage_packagea

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestMessage struct {
	FieldBool            bool     `protobuf:"varint,1,opt,name=field_bool,json=fieldBool,proto3" json:"field_bool,omitempty"`
	FieldI32             int32    `protobuf:"varint,2,opt,name=field_i32,json=fieldI32,proto3" json:"field_i32,omitempty"`
	FieldS32             int32    `protobuf:"zigzag32,3,opt,name=field_s32,json=fieldS32,proto3" json:"field_s32,omitempty"`
	BytesField           []byte   `protobuf:"bytes,4,opt,name=bytes_field,json=bytesField,proto3" json:"bytes_field,omitempty"`
	FieldU32             uint32   `protobuf:"varint,5,opt,name=field_u32,json=fieldU32,proto3" json:"field_u32,omitempty"`
	FieldU64             uint64   `protobuf:"varint,6,opt,name=field_u64,json=fieldU64,proto3" json:"field_u64,omitempty"`
	FieldS64             int64    `protobuf:"zigzag64,7,opt,name=field_s64,json=fieldS64,proto3" json:"field_s64,omitempty"`
	StringField          string   `protobuf:"bytes,8,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMessage) Reset()         { *m = TestMessage{} }
func (m *TestMessage) String() string { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()    {}
func (*TestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_44591ff926c61195, []int{0}
}

func (m *TestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage.Unmarshal(m, b)
}
func (m *TestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage.Marshal(b, m, deterministic)
}
func (m *TestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage.Merge(m, src)
}
func (m *TestMessage) XXX_Size() int {
	return xxx_messageInfo_TestMessage.Size(m)
}
func (m *TestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage proto.InternalMessageInfo

func (m *TestMessage) GetFieldBool() bool {
	if m != nil {
		return m.FieldBool
	}
	return false
}

func (m *TestMessage) GetFieldI32() int32 {
	if m != nil {
		return m.FieldI32
	}
	return 0
}

func (m *TestMessage) GetFieldS32() int32 {
	if m != nil {
		return m.FieldS32
	}
	return 0
}

func (m *TestMessage) GetBytesField() []byte {
	if m != nil {
		return m.BytesField
	}
	return nil
}

func (m *TestMessage) GetFieldU32() uint32 {
	if m != nil {
		return m.FieldU32
	}
	return 0
}

func (m *TestMessage) GetFieldU64() uint64 {
	if m != nil {
		return m.FieldU64
	}
	return 0
}

func (m *TestMessage) GetFieldS64() int64 {
	if m != nil {
		return m.FieldS64
	}
	return 0
}

func (m *TestMessage) GetStringField() string {
	if m != nil {
		return m.StringField
	}
	return ""
}

func init() {
	proto.RegisterType((*TestMessage)(nil), "basicmessage.packagea.TestMessage")
}

func init() { proto.RegisterFile("a.proto", fileDescriptor_44591ff926c61195) }

var fileDescriptor_44591ff926c61195 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0x47, 0x99, 0xda, 0x3f, 0xdb, 0xd9, 0x7a, 0x30, 0x20, 0x04, 0x44, 0x1c, 0x3d, 0xcd, 0xa9,
	0x87, 0x64, 0xd9, 0x0f, 0xe0, 0x41, 0xf0, 0xe0, 0x65, 0xd5, 0xf3, 0x92, 0xd4, 0xb8, 0x04, 0x57,
	0x53, 0x9a, 0xf4, 0xe0, 0xd1, 0x6f, 0x2e, 0xcd, 0x6e, 0x69, 0x8f, 0x79, 0x8f, 0x5f, 0x1e, 0x0c,
	0x2e, 0xcc, 0x7a, 0xbb, 0x0b, 0x29, 0x88, 0x6b, 0x6b, 0xa2, 0xdf, 0x7c, 0xbb, 0x18, 0x4d, 0xe7,
	0xd6, 0x5b, 0xb3, 0xf9, 0x32, 0x9d, 0x33, 0x0f, 0x7f, 0x13, 0x2c, 0xdf, 0x5c, 0x4c, 0x2f, 0x83,
	0x10, 0xb7, 0x88, 0x9f, 0xde, 0xf5, 0x1f, 0xad, 0x0d, 0xa1, 0x97, 0x40, 0xc0, 0x45, 0xb3, 0xcc,
	0xe4, 0x31, 0x84, 0x5e, 0xdc, 0xe0, 0xf0, 0x68, 0xbd, 0x56, 0x72, 0x42, 0xc0, 0xb3, 0xa6, 0xc8,
	0xe0, 0x59, 0xab, 0x93, 0x8c, 0x5a, 0xc9, 0x0b, 0x02, 0xbe, 0x1a, 0xe5, 0xab, 0x56, 0xe2, 0x0e,
	0x4b, 0xfb, 0x9b, 0x5c, 0x6c, 0x33, 0x91, 0x53, 0x02, 0x5e, 0x35, 0x98, 0xd1, 0xd3, 0x81, 0x9c,
	0xd6, 0x7b, 0xad, 0xe4, 0x8c, 0x80, 0x2f, 0xc7, 0xf5, 0xfb, 0xf9, 0xd7, 0xfb, 0xba, 0x92, 0x73,
	0x02, 0x9e, 0x1e, 0x65, 0x5d, 0x9d, 0x75, 0xeb, 0x4a, 0x2e, 0x08, 0x58, 0x1c, 0xbb, 0x75, 0x25,
	0xee, 0x71, 0x15, 0xd3, 0xce, 0xff, 0x74, 0x63, 0xb8, 0x20, 0xe0, 0x65, 0x53, 0x0e, 0x2c, 0x97,
	0xed, 0x3c, 0x5f, 0x48, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x24, 0x18, 0xb5, 0x31, 0x2c, 0x01,
	0x00, 0x00,
}
